# hexo-theme-indigo
# https://github.com/dinphy/hexo-theme-indigo

# 关键字
keyWords: Dinphy 的博客，我的博客，我来作主 <br /> 专注于研究：Web 前端开发，Nodejs 后端开发，混合式移动应用开发，Javascript 全栈式开发，数据挖掘与可视化 等技术。

# 额外的信息
author: Dinphy
career: 大前端开发工程师
summary: 温故而知新，可以为师矣。

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archives:
    text: 归档
    url: /archives
  tags:
    text: 标签
    url: /tags
  th-list:
    text: 分类
    url: /categories
  user:
    text: 关于
    url: /menu/about.html
  #share:
  #  text: 干货
  #  url: /menu/share.html
  # star:
  #   text: 读书
  #   url: /menu/study.html
  #star:
  #  text: 计划
  #  url: /menu/plan.html
  #book:
  #  text: Gitbook
  #  url: /menu/book.html
  #google:
  #  text: Npm
  #  url: /menu/npm.html
  #github:
  #  url: https://github.com/lizhooh
  #  target: _blank
  # car:
  #   text: 'Devhint'
  #   url: https://devhints.io/
  #   target: _blank

  # link:
  #   text: 测试
  #   url: /custom

rss: /atom.xml

# 你的头像url
avatar: /img/avatar.jpg
# favicon
favicon: /img/favicon.ico

# email
email: 2027821710@qq.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: #33AAFF
# 页面标题
tags_title: 标签
archives_title: 归档
categories_title: 分类

# 文章截断
excerpt_render: true
excerpt_length: 250
excerpt_link: 阅读全文...
mathjax: false
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward:
  title:                  谢谢您的鼓励，扫一扫吧(๑•ᴗ•๑)~
  wechat:                 /img/wechat.gif     #微信，关闭设为 false
  alipay:                 /img/alipay.gif     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: true

# 是否开启 toc
# toc: false
toc:
  list_number: true  # 是否显示数字排序

# 文章页版权声明内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
#copyright: <br /><b style="color:#f66">版权声明</b> - Lizhooh，未经允许禁止转载！！！经允许的请声明：<div style='height:8px'></div><b>作者</b>：Lizhooh 前端开发工程师<br /><b>原文</b>：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- url.replace(/index\.html$/, '') %></a>

# Post License | 在每篇文章的结尾添加你的版权说明
# You can specify the text you want to show in the end of your posts and pages, HTML tag is supported.
#   For example, you can setup a CC license as:
#       'This blog is under a <a href="/creativecommons.html" target="_blank">CC BY-NC-SA 3.0 Unported License</a>'
# You can also use Front-Matter `license` to override this setting.
license: "<b>本文采用：署名-非商业性使用-禁止演绎 4.0 国际</b> 协议进行许可，阅读 <a rel='nofollow noopener' href='https://creativecommons.org/licenses/by-nc-nd/4.0/deed.zh' target='_blank'>相关说明</a>"

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
baidu_tongji: false

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# less
less:
  compress: true             # 压缩
  paths:
    - source/css/style.less

# 是否开启多说评论，填写你在多说创建的站点二级域名
# duoshuo: ysblog
# duoshuo: false
# 是否开启多说评论计数（该服务不稳定）
# duoshuo_count: false
# 使用 disqus 时关闭多说评论
# disqus_shortname: false

# Valine Comment system. https://valine.js.org | Valine评论系统
valine:
  enable: true # 如果你想使用valine，请将值设置为 true
  appId: EdyGwWrx3Uxu5hRnY4d4pswD-gzGzoHsz # your leancloud appId
  appKey: 4pmmj56YRbawceTeHCkLMT7n # your leancloud appKey
  notify: false # Mail notify
  verify: false # Verify code
  avatar: mm # Gravatar style : mm/identicon/monsterid/wavatar/retro/hide
  placeholder: Hi,留下您的足迹吧~ # Comment Box placeholder
  guest_info: nick,mail,link # Comment header info
  pageSize: 10 # comment list page size

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: https://dinphy.github.io

# 版权起始年份
since_year: 2017

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: 不忘初心,继续前行

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
visit_counter:
  site_uv: 总访客数：
  site_pv: 总访问量：

# 音乐 id，是否开启
music: false
musicid: 0

